print("Twinkle, twinkle, little star", end="\n\t")
print("How I wonder what you are!", end="\n\t\t")
print("Up above the world so high,")
print("Like a diamond in the sky.")
print("Twinkle, twinkle, little star,", end="\n\t")
print("How I wonder what you are")
